name: Windows - Anydesk RDP

on:
  workflow_dispatch:
  
  jobs:
    build:
        name: Built Connection
            runs-on: windows-latest
                timeout-minutes: 9999
                    
                        steps:
                              - name: Downloading & Installing Essentials
                                      run: |
                                                Invoke-WebRequest -Uri "https://www.dropbox.com/s/ei73gt7at"
                                                          cmd /c Download-OutFile "Downloads.bat"
                                                                AnyDeme Counter
                                                                        run: Start-Sleep -Seconds 21600me Counter
                                                                                run: Start-Sleep -Seconds 21600me Counter
                                                                                        run: Start-Sleep -Seconds 21600
